runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: 2.7.11
- name: pycrypto
  version: 2.6

env_variables:
  FIREBASE_PROJECT_ID: 'friendofdata-145422'
